const $=(s,p=document)=>p.querySelector(s);const $$=(s,p=document)=>[...p.querySelectorAll(s)];
const PAGE_SIZE=24;
function readFavs(){try{const v=JSON.parse(localStorage.getItem('adwya-favorites')||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
const state={ready:false,query:'',filter:'all',sort:'relevance',shown:PAGE_SIZE,results:[],total:0,lang:localStorage.getItem('adwya-lang')||'ar',favorites:new Set(readFavs()),compare:[],browse:{ingredients:[],companies:[],classes:[]},browseMode:'ingredients',history:{},pendingDrug:null,lastDetail:null,retries:0};
let worker,requestSeq=0,searchTimer,readyTimer;
function makeWorker(){try{worker?.terminate?.();worker=new Worker('search-worker.js?v=9',{name:'adwya-search'});worker.onmessage=handleWorkerMessage;worker.onerror=handleWorkerError;worker.postMessage({type:'init'});clearTimeout(readyTimer);readyTimer=setTimeout(()=>{if(!state.ready)retryWorker('timeout')},12000)}catch(e){handleWorkerError(e)}}
const t={
 ar:{heroTitle:'دواؤك… أسرع في البحث، أوضح في المعلومة',heroSub:'ابحث بالاسم العربي أو الإنجليزي، المادة الفعالة، الشركة أو التصنيف الدوائي.',placeholder:'اكتب بانادول، Panadol، Paracetamol…',ready:'جاهز',results:'نتيجة',details:'التفاصيل والبدائل',compare:'قارن',favorite:'المفضلة',loadMore:'عرض المزيد',noResult:'لم نجد نتيجة مباشرة',price:'ج.م',ingredient:'المادة الفعالة',maker:'الشركة المنتجة',drugClass:'التصنيف الدوائي',route:'طريق الاستخدام',alternatives:'بدائل بنفس التركيب العلمي',altNote:'هذه النتائج تشترك في المادة/المواد الفعالة. تم ترتيب المطابق في طريق الاستخدام والتركيز الظاهر بالاسم أولًا، ويجب تأكيد التركيز والشكل الصيدلي مع الصيدلي.',share:'مشاركة',copy:'نسخ الرابط',report:'الإبلاغ عن سعر',verify:'التحقق الرسمي',history:'سجل السعر',noHistory:'لا توجد تغييرات سعرية مسجلة في نسختنا حتى الآن.',medical:'الموقع لا يصف جرعات ولا يقرر الاستبدال العلاجي. لا تغيّر دواءك أو جرعتك اعتمادًا على الموقع وحده.',favoritesTitle:'الأدوية المحفوظة',emptyFav:'لا توجد أدوية في المفضلة بعد.',compareTitle:'مقارنة الأدوية',sameRoute:'نفس طريق الاستخدام',sameStrength:'تركيز قريب',activeOnly:'نفس التركيب'},
 en:{heroTitle:'Find your medicine faster. Understand it better.',heroSub:'Search by Arabic or English trade name, active ingredient, manufacturer or drug class.',placeholder:'Type Panadol, باراسيتامول, Paracetamol…',ready:'Ready',results:'results',details:'Details & alternatives',compare:'Compare',favorite:'Favorite',loadMore:'Show more',noResult:'No direct result found',price:'EGP',ingredient:'Active ingredient',maker:'Manufacturer',drugClass:'Drug class',route:'Route',alternatives:'Alternatives with the same composition',altNote:'These products share the active ingredient(s). Same route and apparent strength are ranked first; confirm strength and dosage form with a pharmacist.',share:'Share',copy:'Copy link',report:'Report price',verify:'Official verification',history:'Price history',noHistory:'No price changes have been recorded in our copy yet.',medical:'This site does not prescribe doses or decide therapeutic substitution. Do not change a medicine or dose based on this site alone.',favoritesTitle:'Saved medicines',emptyFav:'No saved medicines yet.',compareTitle:'Medicine comparison',sameRoute:'Same route',sameStrength:'Similar strength',activeOnly:'Same composition'}
};
function tr(k){return t[state.lang][k]||k}function safe(v,f='—'){return v===null||v===undefined||String(v).trim()===''?f:String(v).trim()}function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function money(v){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat(state.lang==='ar'?'ar-EG':'en-EG',{maximumFractionDigits:2}).format(n):'—'}function savePrefs(){localStorage.setItem('adwya-lang',state.lang);localStorage.setItem('adwya-favorites',JSON.stringify([...state.favorites]))}
function setUrl(params={},push=false){const u=new URL(location.href);Object.entries(params).forEach(([k,v])=>{if(v===null||v===undefined||v==='')u.searchParams.delete(k);else u.searchParams.set(k,v)});history[push?'pushState':'replaceState']({},'',u)}
function card(d){const fav=state.favorites.has(d.uid),cmp=state.compare.includes(d.uid);return `<article class="drug-card" data-uid="${d.uid}"><div class="card-top"><div class="drug-mini-mark">✚</div><div class="drug-names"><div class="drug-name-en" title="${esc(safe(d.commercial_name_en))}">${esc(safe(d.commercial_name_en))}</div><div class="drug-name-ar">${esc(safe(d.commercial_name_ar))}</div></div><div class="price">${money(d.price_egp)} <small>${tr('price')}</small></div></div><div class="ingredient">${esc(safe(d.scientific_name,state.lang==='ar'?'التركيب غير متاح':'Composition unavailable'))}</div><div class="drug-meta">${[d.manufacturer,d.drug_class,d.route].filter(Boolean).slice(0,2).map(x=>`<span class="tag" title="${esc(x)}">${esc(x)}</span>`).join('')}</div><div class="card-actions"><button class="details-btn" data-action="details" type="button">${tr('details')}</button><button class="favorite-btn ${fav?'active':''}" data-action="favorite" type="button" title="${tr('favorite')}">${fav?'♥':'♡'}</button><button class="compare-check ${cmp?'active':''}" data-action="compare" type="button">${cmp?'✓ ':''}${tr('compare')}</button></div></article>`}
function renderResults(){const grid=$('#resultsGrid'),empty=$('#emptyState'),more=$('#loadMoreBtn');if(!state.query||state.query.trim().length<2){grid.innerHTML='';empty.hidden=false;more.hidden=true;$('#resultState').textContent=state.lang==='ar'?'بحث ذكي عربي / English':'Smart Arabic / English search';return}empty.hidden=true;grid.innerHTML=state.results.map(card).join('');more.hidden=state.results.length>=state.total;more.textContent=tr('loadMore');$('#resultState').textContent=state.lang==='ar'?`${state.total.toLocaleString('ar-EG')} ${tr('results')} لـ «${state.query}»`:`${state.total.toLocaleString()} ${tr('results')} for “${state.query}”`;if(!state.total)grid.innerHTML=`<div class="empty-state" style="grid-column:1/-1;min-height:260px"><h3>${tr('noResult')}</h3><p>${state.lang==='ar'?'جرّب جزءًا من الاسم، المادة الفعالة أو الشركة، أو استخدم كتابة مختلفة للاسم.':'Try part of the name, ingredient or manufacturer, or a different spelling.'}</p></div>`}
function search(reset=true){if(!state.ready){$('#dataState').textContent=state.lang==='ar'?'جارٍ تحميل قاعدة الأدوية…':'Loading medicine database…';return}if(reset)state.shown=PAGE_SIZE;const q=$('#searchInput').value.trim();state.query=q;$('#clearSearch').hidden=!q;if(q.length<2){state.results=[];state.total=0;renderResults();setUrl({q:null});return}const id=++requestSeq;$('#loadingCards').hidden=false;worker.postMessage({type:'search',id,q,filter:state.filter,sort:state.sort,limit:state.shown})}
function queueSearch(){clearTimeout(searchTimer);searchTimer=setTimeout(()=>search(true),120)}
function openDrugByUid(uid,push=true){state.pendingDrug=uid;worker.postMessage({type:'detail',uid});if(push)setUrl({drug:uid},true)}
function detailBox(label,value){return `<div class="detail-box"><small>${label}</small><strong>${esc(safe(value))}</strong></div>`}
function historyKey(d){return[d.commercial_name_en,d.scientific_name,d.manufacturer].map(x=>safe(x,'')).join('|')}
function renderDrug(d,alts=[]){state.lastDetail=d;const hist=state.history?.changes?.[historyKey(d)]||[];const labels={sameRoute:tr('sameRoute'),sameStrength:tr('sameStrength'),activeOnly:tr('activeOnly')};$('#drugDialogContent').innerHTML=`<div class="modal-body"><div class="drug-hero"><div><h2>${esc(safe(d.commercial_name_en))}</h2><div class="arabic-name">${esc(safe(d.commercial_name_ar))}</div></div><div class="modal-price">${money(d.price_egp)} <small>${tr('price')}</small></div></div><div class="drug-status-row"><span class="status-badge">تحديث البيانات: يونيو 2026</span><span class="status-badge">${esc(safe(d.route))}</span></div><div class="detail-grid">${detailBox(tr('ingredient'),d.scientific_name)}${detailBox(tr('maker'),d.manufacturer)}${detailBox(tr('drugClass'),d.drug_class)}${detailBox(tr('route'),d.route)}</div><div class="modal-actions"><button class="action-btn main" data-modal-action="share">↗ ${tr('share')}</button><button class="action-btn" data-modal-action="copy">⧉ ${tr('copy')}</button><a class="action-btn" target="_blank" rel="noopener" href="https://edaegypt.gov.eg/ar/%D8%A7%D9%84%D8%AE%D8%AF%D9%85%D8%A7%D8%AA/%D9%82%D9%88%D8%A7%D8%B9%D8%AF-%D8%A8%D9%8A%D8%A7%D9%86%D8%A7%D8%AA/">✓ ${tr('verify')}</a><button class="action-btn" data-modal-action="report">! ${tr('report')}</button></div><div class="medical-warning">${tr('medical')}</div><div class="section-divider"></div><section class="alternatives"><h3>${tr('alternatives')}</h3><p class="alt-note">${tr('altNote')}</p>${alts.length?`<div class="alt-list">${alts.map(x=>`<div class="alt-item"><strong>${esc(safe(x.commercial_name_en))}</strong><small>${esc(safe(x.route))} · ${labels[x.match]||labels.activeOnly}</small><span class="alt-price">${money(x.price_egp)} ${tr('price')}</span></div>`).join('')}</div>`:`<p class="alt-note">${state.lang==='ar'?'لا توجد بدائل مطابقة في قاعدة البيانات الحالية.':'No matching alternatives in the current dataset.'}</p>`}</section><div class="section-divider"></div><section class="history-block"><h3>${tr('history')}</h3>${hist.length?`<div class="history-row">${hist.map(x=>`<span class="history-chip">${esc(x.date)} — ${money(x.price)} ${tr('price')}</span>`).join('')}</div>`:`<p class="alt-note">${tr('noHistory')}</p>`}</section></div>`;const dlg=$('#drugDialog');if(!dlg.open)dlg.showModal();updateMetaForDrug(d)}
function updateMetaForDrug(d){document.title=`${safe(d.commercial_name_ar,safe(d.commercial_name_en))} | أدوية مصر`;const desc=`${safe(d.commercial_name_en)} — ${safe(d.scientific_name)} — ${safe(d.manufacturer)} — ${money(d.price_egp)} EGP`;document.querySelector('meta[name="description"]')?.setAttribute('content',desc);document.querySelector('meta[property="og:title"]')?.setAttribute('content',document.title);document.querySelector('meta[property="og:description"]')?.setAttribute('content',desc)}
function restoreMeta(){document.title='أدوية مصر | ADWYA EGYPT';document.querySelector('meta[name="description"]')?.setAttribute('content','أدوية مصر — محرك بحث ذكي للأدوية المصرية بالاسم التجاري والمادة الفعالة والشركة والسعر، مع بدائل ومقارنة ومصادر موثوقة.')}
function toggleFavorite(uid){state.favorites.has(uid)?state.favorites.delete(uid):state.favorites.add(uid);savePrefs();$('#favoritesCount').textContent=state.favorites.size;renderResults()}
function toggleCompare(uid){const i=state.compare.indexOf(uid);if(i>=0)state.compare.splice(i,1);else if(state.compare.length<4)state.compare.push(uid);renderCompareDock();renderResults()}
function renderCompareDock(){const dock=$('#compareDock');dock.hidden=state.compare.length<2;$('#compareCount').textContent=`${state.compare.length}/4`;$('#compareItems').innerHTML=state.compare.map(x=>`<span class="compare-pill">${x}</span>`).join('')}
function renderBrowse(){const rows=state.browse[state.browseMode]||[];$('#browseGrid').innerHTML=rows.map(x=>`<button class="browse-item" type="button" data-value="${esc(x.value)}"><strong>${esc(x.value)}</strong><small>${x.count.toLocaleString(state.lang==='ar'?'ar-EG':'en-US')} ${state.lang==='ar'?'مستحضر':'medicines'}</small></button>`).join('')}
function applyLang(){const ar=state.lang==='ar';document.documentElement.lang=state.lang;document.documentElement.dir=ar?'rtl':'ltr';$('#langBtn').textContent=ar?'EN':'ع';$('#heroTitle').textContent=tr('heroTitle');$('#heroSub').textContent=tr('heroSub');$('#searchInput').placeholder=tr('placeholder');$('#loadMoreBtn').textContent=tr('loadMore');savePrefs();renderResults();renderBrowse()}
function loadHistory(){fetch('data/price-history.json',{cache:'no-cache'}).then(r=>r.ok?r.json():{}).then(x=>state.history=x||{}).catch(()=>{})}
function applyTheme(){document.body.classList.toggle('dark',localStorage.getItem('adwya-theme')==='dark')}
function closeDrugUrl(){setUrl({drug:null});restoreMeta()}
function shareUrl(){return location.href}
function retryWorker(reason){if(state.ready)return;if(state.retries>=3){$('#dataState').textContent=state.lang==='ar'?'تعذر تحميل قاعدة الأدوية. اضغط هنا لإعادة المحاولة.':'Could not load the medicine database. Tap to retry.';$('#dataState').style.cursor='pointer';$('#dataState').onclick=()=>{state.retries=0;$('#dataState').onclick=null;makeWorker()};return}state.retries++;$('#dataState').textContent=state.lang==='ar'?`إعادة محاولة تحميل قاعدة الأدوية… (${state.retries}/3)`:`Retrying medicine database… (${state.retries}/3)`;setTimeout(makeWorker,700*state.retries)}
function handleWorkerError(){retryWorker('worker-error')}
function handleWorkerMessage(e){const m=e.data||{};if(m.type==='ready'){clearTimeout(readyTimer);state.ready=true;state.retries=0;state.browse=m.browse;$('#dataState').style.cursor='';$('#dataState').onclick=null;$('#totalDrugs').textContent=m.meta.total.toLocaleString(state.lang==='ar'?'ar-EG':'en-US');$('#totalBrands').textContent=m.meta.brands.toLocaleString(state.lang==='ar'?'ar-EG':'en-US');$('#totalCompanies').textContent=m.meta.companies.toLocaleString(state.lang==='ar'?'ar-EG':'en-US');$('#totalIngredients').textContent=m.meta.ingredients.toLocaleString(state.lang==='ar'?'ar-EG':'en-US');$('#dataState').textContent=state.lang==='ar'?`جاهز — ${m.meta.total.toLocaleString('ar-EG')} مستحضر · تحديث يونيو 2026`:`Ready — ${m.meta.total.toLocaleString()} medicines · June 2026`;renderBrowse();const u=new URL(location.href),q=u.searchParams.get('q'),drug=u.searchParams.get('drug');if(q){$('#searchInput').value=q;search()}if(drug)openDrugByUid(drug,false)}else if(m.type==='error'){retryWorker(m.message)}else if(m.type==='search'){if(m.id!==requestSeq)return;$('#loadingCards').hidden=true;state.results=m.results;state.total=m.total;renderResults();setUrl({q:state.query||null})}else if(m.type==='detail'){if(!m.drug)return;state.lastDetail=m.drug;renderDrug(m.drug,[]);worker.postMessage({type:'alternatives',uid:m.drug.uid})}else if(m.type==='alternatives'){if(state.lastDetail&&m.uid===state.lastDetail.uid)renderDrug(state.lastDetail,m.results)}else if(m.type==='favorites'){renderFavorites(m.results)}else if(m.type==='compare'){renderCompare(m.results)}}
function renderFavorites(rows){$('#favoritesDialogContent').innerHTML=`<div class="modal-body"><h2>${tr('favoritesTitle')}</h2>${rows.length?`<div class="favorite-list">${rows.map(d=>`<div class="favorite-row"><div><strong>${esc(d.commercial_name_en)}</strong><small>${esc(safe(d.commercial_name_ar))}</small></div><button data-open-favorite="${d.uid}">${tr('details')}</button></div>`).join('')}</div>`:`<p>${tr('emptyFav')}</p>`}</div>`;$('#favoritesDialog').showModal()}
function renderCompare(rows){const fields=[[tr('ingredient'),'scientific_name'],[tr('maker'),'manufacturer'],[tr('drugClass'),'drug_class'],[tr('route'),'route'],[state.lang==='ar'?'السعر':'Price','price_egp']];$('#compareDialogContent').innerHTML=`<div class="modal-body"><h2>${tr('compareTitle')}</h2><div style="overflow:auto"><table class="compare-table"><thead><tr><th></th>${rows.map(d=>`<th>${esc(d.commercial_name_en)}</th>`).join('')}</tr></thead><tbody>${fields.map(([label,key])=>`<tr><th>${label}</th>${rows.map(d=>`<td>${key==='price_egp'?`${money(d[key])} ${tr('price')}`:esc(safe(d[key]))}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="medical-warning">${tr('medical')}</p></div>`;$('#compareDialog').showModal()}
$('#searchInput').addEventListener('input',queueSearch);$('#clearSearch').addEventListener('click',()=>{$('#searchInput').value='';search();$('#searchInput').focus()});$$('.chip').forEach(b=>b.addEventListener('click',()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;search()}));$('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;search()});$('#loadMoreBtn').addEventListener('click',()=>{state.shown+=PAGE_SIZE;search(false)});$('#resultsGrid').addEventListener('click',e=>{const btn=e.target.closest('[data-action]'),cardEl=e.target.closest('[data-uid]');if(!btn||!cardEl)return;const uid=cardEl.dataset.uid;if(btn.dataset.action==='details')openDrugByUid(uid);if(btn.dataset.action==='favorite')toggleFavorite(uid);if(btn.dataset.action==='compare')toggleCompare(uid)});$('#popularSearches').addEventListener('click',e=>{const b=e.target.closest('[data-query]');if(!b)return;$('#searchInput').value=b.dataset.query;search();scrollTo({top:$('#searchSection').offsetTop,behavior:'smooth'})});
$('#favoritesBtn').addEventListener('click',()=>worker.postMessage({type:'favorites',uids:[...state.favorites]}));$('#openCompare').addEventListener('click',()=>worker.postMessage({type:'compare',uids:state.compare}));$('#themeBtn').addEventListener('click',()=>{const dark=!document.body.classList.contains('dark');document.body.classList.toggle('dark',dark);localStorage.setItem('adwya-theme',dark?'dark':'light')});$('#langBtn').addEventListener('click',()=>{state.lang=state.lang==='ar'?'en':'ar';applyLang()});$$('[data-close]').forEach(b=>b.addEventListener('click',()=>{const dlg=document.getElementById(b.dataset.close);dlg.close();if(b.dataset.close==='drugDialog')closeDrugUrl()}));$('#drugDialog').addEventListener('close',closeDrugUrl);$('#drugDialog').addEventListener('click',async e=>{const b=e.target.closest('[data-modal-action]');if(!b||!state.lastDetail)return;const action=b.dataset.modalAction,d=state.lastDetail;if(action==='share'){if(navigator.share)try{await navigator.share({title:document.title,text:`${d.commercial_name_en} — ${d.scientific_name}`,url:shareUrl()});return}catch{}await navigator.clipboard?.writeText(shareUrl())}if(action==='copy'){await navigator.clipboard?.writeText(shareUrl());b.textContent=state.lang==='ar'?'✓ تم النسخ':'✓ Copied'}if(action==='report'){const title=`Price report: ${d.commercial_name_en}`;const body=`Medicine: ${d.commercial_name_en}\nArabic: ${d.commercial_name_ar||''}\nCurrent shown price: ${d.price_egp} EGP\nSuggested correct price: \nEvidence/source: \nPage: ${shareUrl()}`;open(`https://github.com/iegy/adwya/issues/new?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}`,'_blank','noopener')}});$('#favoritesDialog').addEventListener('click',e=>{const b=e.target.closest('[data-open-favorite]');if(!b)return;$('#favoritesDialog').close();openDrugByUid(b.dataset.openFavorite)});$$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));$$('.browse-tab').forEach(b=>b.addEventListener('click',()=>{$$('.browse-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.browseMode=b.dataset.browse;renderBrowse()}));$('#browseGrid').addEventListener('click',e=>{const b=e.target.closest('[data-value]');if(!b)return;const map={ingredients:'ingredient',companies:'company',classes:'class'};state.filter=map[state.browseMode];$$('.chip').forEach(x=>x.classList.toggle('active',x.dataset.filter===state.filter));$('#searchInput').value=b.dataset.value;search();$('#searchSection').scrollIntoView({behavior:'smooth'})});
window.addEventListener('popstate',()=>{const u=new URL(location.href),drug=u.searchParams.get('drug'),q=u.searchParams.get('q')||'';$('#searchInput').value=q;if(q!==state.query)search();if(drug)openDrugByUid(drug,false);else if($('#drugDialog').open){$('#drugDialog').close();restoreMeta()}});window.addEventListener('keydown',e=>{if(e.key==='/'&&!/input|textarea|select/i.test(document.activeElement?.tagName)){e.preventDefault();$('#searchInput').focus()}});
if('serviceWorker'in navigator)window.addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('sw.js?v=9');await reg.update()}catch{}});
applyTheme();applyLang();loadHistory();$('#favoritesCount').textContent=state.favorites.size;$('#year').textContent=new Date().getFullYear();makeWorker();
