const DATA_URL='https://raw.githubusercontent.com/karem505/egyptian-drug-database/main/data/egyptian-drugs.json';
const DATASET_UPDATED='يونيو 2026';
const PAGE_SIZE=24;

const $=(s,p=document)=>p.querySelector(s);const $$=(s,p=document)=>[...p.querySelectorAll(s)];
const state={drugs:[],view:[],shown:PAGE_SIZE,filter:'all',sort:'relevance',query:'',lang:localStorage.getItem('adwya-lang')||'ar',favorites:new Set(JSON.parse(localStorage.getItem('adwya-favorites')||'[]')),compare:[],ready:false};

const i18n={
 ar:{datasetStatus:'قاعدة أدوية مصرية محدثة',heroTitle:'دواؤك… أسرع في البحث، أوضح في المعلومة',heroSub:'ابحث بالاسم العربي أو الإنجليزي، المادة الفعالة، الشركة أو التصنيف الدوائي.',searchPlaceholder:'اكتب بانادول، Panadol، Paracetamol…',filterAll:'الكل',filterName:'الاسم التجاري',filterIngredient:'المادة الفعالة',filterCompany:'الشركة',filterClass:'التصنيف',loadingData:'جارٍ تجهيز قاعدة الأدوية…',smartSearch:'بحث ذكي عربي / English',statDrugs:'مستحضر',statBrands:'اسم تجاري',statCompanies:'شركة',statCurrency:'أسعار بالجنيه',whyTitle:'معلومة أوضح',whyText:'نعرض السعر مع مصدر البيانات وتاريخ التحديث، ونفصل بين طريق الاستخدام والجرعة الطبية.',resultsEyebrow:'محرك البحث',resultsTitle:'اكتشف الأدوية',sortRelevant:'الأكثر صلة',sortPriceAsc:'السعر: الأقل أولًا',sortPriceDesc:'السعر: الأعلى أولًا',sortName:'الاسم',emptyTitle:'ابدأ بكتابة اسم دواء أو مادة فعالة',emptyText:'سنبحث في الاسم التجاري، المادة الفعالة، الشركة والتصنيف في نفس اللحظة.',loadMore:'عرض المزيد',medicalTitle:'تنبيه طبي',medicalText:'الموقع مرجع معلوماتي ولا يحدد جرعتك ولا يستبدل الطبيب أو الصيدلي. الأسعار قد تتغير.',compareTitle:'المقارنة',compareNow:'قارن الآن',footerSource:'بيانات الأسعار للاسترشاد ويجب التحقق منها وقت الشراء. مصدر البيانات المفتوحة مذكور داخل الموقع.'},
 en:{datasetStatus:'Updated Egyptian medicine dataset',heroTitle:'Find your medicine faster. Understand it better.',heroSub:'Search by Arabic or English trade name, active ingredient, manufacturer or drug class.',searchPlaceholder:'Type Panadol, باراسيتامول, Paracetamol…',filterAll:'All',filterName:'Trade name',filterIngredient:'Ingredient',filterCompany:'Manufacturer',filterClass:'Drug class',loadingData:'Preparing medicines database…',smartSearch:'Smart Arabic / English search',statDrugs:'medicines',statBrands:'trade names',statCompanies:'companies',statCurrency:'prices in EGP',whyTitle:'Clearer information',whyText:'Prices include dataset source and update date. Route of administration is kept separate from medical dosing.',resultsEyebrow:'Search engine',resultsTitle:'Explore medicines',sortRelevant:'Most relevant',sortPriceAsc:'Price: low to high',sortPriceDesc:'Price: high to low',sortName:'Name',emptyTitle:'Start with a medicine or ingredient',emptyText:'We search trade names, ingredients, manufacturers and classes at the same time.',loadMore:'Show more',medicalTitle:'Medical notice',medicalText:'This site is informational. It does not prescribe a dose or replace a doctor or pharmacist. Prices can change.',compareTitle:'Compare',compareNow:'Compare now',footerSource:'Prices are indicative and should be verified when buying. The open dataset source is disclosed on this site.'}
};

function normalize(v=''){return String(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[إأآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/ة/g,'ه').replace(/[ًٌٍَُِّْـ]/g,'').replace(/[^a-z0-9\u0600-\u06ff]+/g,' ').trim()}
function grams(s){s=normalize(s).replace(/\s/g,'');if(s.length<2)return[s];let g=[];for(let i=0;i<s.length-1;i++)g.push(s.slice(i,i+2));return g}
function dice(a,b){const A=grams(a),B=grams(b);if(!A.length||!B.length)return 0;const m=new Map;A.forEach(x=>m.set(x,(m.get(x)||0)+1));let hit=0;B.forEach(x=>{const n=m.get(x)||0;if(n){hit++;m.set(x,n-1)}});return 2*hit/(A.length+B.length)}
function safe(v,fallback='—'){return v===null||v===undefined||String(v).trim()===''?fallback:String(v).trim()}
function money(v){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat(state.lang==='ar'?'ar-EG':'en-EG',{maximumFractionDigits:2}).format(n):safe(v)}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function savePrefs(){localStorage.setItem('adwya-favorites',JSON.stringify([...state.favorites]));localStorage.setItem('adwya-lang',state.lang)}
function drugId(d){return `${d.commercial_name_en||''}|${d.scientific_name||''}|${d.manufacturer||''}|${d.price_egp||''}`}

async function idbGet(){return new Promise(resolve=>{const req=indexedDB.open('adwya-db',1);req.onupgradeneeded=()=>req.result.createObjectStore('cache');req.onerror=()=>resolve(null);req.onsuccess=()=>{const db=req.result,tx=db.transaction('cache','readonly'),r=tx.objectStore('cache').get('drugs-v1');r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>resolve(null)}})}
async function idbSet(value){return new Promise(resolve=>{const req=indexedDB.open('adwya-db',1);req.onupgradeneeded=()=>req.result.createObjectStore('cache');req.onerror=()=>resolve();req.onsuccess=()=>{const tx=req.result.transaction('cache','readwrite');tx.objectStore('cache').put(value,'drugs-v1');tx.oncomplete=()=>resolve();tx.onerror=()=>resolve()}})}

async function loadData(){
 try{
  const cached=await idbGet();
  if(cached?.data?.length){hydrate(cached.data);$('#dataState').textContent=state.lang==='ar'?`جاهز — ${state.drugs.length.toLocaleString('ar-EG')} مستحضر`:`Ready — ${state.drugs.length.toLocaleString()} medicines`;fetchFresh().catch(()=>{});return}
  await fetchFresh(true);
 }catch(e){$('#dataState').textContent=state.lang==='ar'?'تعذر تحميل البيانات. تحقق من الاتصال وأعد المحاولة.':'Could not load data. Check your connection and retry.';console.error(e)}
}
async function fetchFresh(first=false){const res=await fetch(DATA_URL,{cache:'no-cache'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();if(!Array.isArray(data)||data.length<1000)throw new Error('Unexpected dataset');await idbSet({savedAt:Date.now(),data});if(first||!state.ready)hydrate(data)}
function hydrate(data){
 state.drugs=data.map((d,i)=>({...d,_i:i,_id:drugId(d),_n:{en:normalize(d.commercial_name_en),ar:normalize(d.commercial_name_ar),sci:normalize(d.scientific_name),maker:normalize(d.manufacturer),cls:normalize(d.drug_class),route:normalize(d.route)}}));state.ready=true;
 const brands=new Set(state.drugs.map(d=>normalize(d.commercial_name_en)).filter(Boolean));const companies=new Set(state.drugs.map(d=>normalize(d.manufacturer)).filter(Boolean));
 $('#totalDrugs').textContent=state.drugs.length.toLocaleString(state.lang==='ar'?'ar-EG':'en-US');$('#totalBrands').textContent=brands.size.toLocaleString(state.lang==='ar'?'ar-EG':'en-US');$('#totalCompanies').textContent=companies.size.toLocaleString(state.lang==='ar'?'ar-EG':'en-US');$('#dataState').textContent=state.lang==='ar'?`جاهز — ${state.drugs.length.toLocaleString('ar-EG')} مستحضر · تحديث ${DATASET_UPDATED}`:`Ready — ${state.drugs.length.toLocaleString()} medicines · dataset June 2026`;
 if(state.query)runSearch();
}

function scoreDrug(d,q){
 const n=d._n;let score=0;const words=q.split(' ').filter(Boolean);const fields=state.filter==='name'?[n.en,n.ar]:state.filter==='ingredient'?[n.sci]:state.filter==='company'?[n.maker]:state.filter==='class'?[n.cls]:[n.en,n.ar,n.sci,n.maker,n.cls];
 for(const f of fields){if(!f)continue;if(f===q)score=Math.max(score,120);else if(f.startsWith(q))score=Math.max(score,100);else if(f.includes(q))score=Math.max(score,78);for(const w of words){if(f.split(' ').some(x=>x.startsWith(w)))score+=10;if(f.includes(w))score+=5}}
 if(score<40&&q.length>=4){const best=Math.max(dice(q,n.en),dice(q,n.ar));if(best>.62)score+=Math.round(best*55)}
 return score;
}
let timer;function queueSearch(){clearTimeout(timer);timer=setTimeout(runSearch,120)}
function runSearch(){
 if(!state.ready)return;const raw=$('#searchInput').value.trim();state.query=raw;state.shown=PAGE_SIZE;$('#clearSearch').hidden=!raw;
 if(raw.length<2){state.view=[];renderResults();return}
 const q=normalize(raw);let rows=[];for(const d of state.drugs){const score=scoreDrug(d,q);if(score>20)rows.push({d,score})}
 rows.sort((a,b)=>b.score-a.score);state.view=rows.map(x=>({...x.d,_score:x.score}));sortView(false);renderResults();
}
function sortView(render=true){const v=state.view;switch(state.sort){case'priceAsc':v.sort((a,b)=>(Number(a.price_egp)||Infinity)-(Number(b.price_egp)||Infinity));break;case'priceDesc':v.sort((a,b)=>(Number(b.price_egp)||-Infinity)-(Number(a.price_egp)||-Infinity));break;case'name':v.sort((a,b)=>safe(a.commercial_name_en,'').localeCompare(safe(b.commercial_name_en,'')));break;default:v.sort((a,b)=>(b._score||0)-(a._score||0))}if(render)renderResults()}

function card(d){const fav=state.favorites.has(d._id),cmp=state.compare.some(x=>x._id===d._id);const tags=[d.manufacturer,d.drug_class,d.route].filter(Boolean).slice(0,2);return `<article class="drug-card" data-id="${escapeHtml(d._id)}"><div class="card-top"><div class="drug-mini-mark">◉</div><div class="drug-names"><div class="drug-name-en" title="${escapeHtml(safe(d.commercial_name_en))}">${escapeHtml(safe(d.commercial_name_en))}</div><div class="drug-name-ar">${escapeHtml(safe(d.commercial_name_ar))}</div></div><div class="price">${money(d.price_egp)} <small>${state.lang==='ar'?'ج.م':'EGP'}</small></div></div><div class="ingredient">${escapeHtml(safe(d.scientific_name,state.lang==='ar'?'المادة الفعالة غير متاحة':'Ingredient unavailable'))}</div><div class="drug-meta">${tags.map(t=>`<span class="tag" title="${escapeHtml(t)}">${escapeHtml(t)}</span>`).join('')}</div><div class="card-actions"><button class="details-btn" type="button" data-action="details">${state.lang==='ar'?'التفاصيل والبدائل':'Details & alternatives'}</button><button class="favorite-btn ${fav?'active':''}" type="button" data-action="favorite" title="${state.lang==='ar'?'المفضلة':'Favorite'}">${fav?'♥':'♡'}</button><button class="compare-check ${cmp?'active':''}" type="button" data-action="compare">${cmp?'✓ ':''}${state.lang==='ar'?'قارن':'Compare'}</button></div></article>`}
function renderResults(){const grid=$('#resultsGrid'),empty=$('#emptyState'),btn=$('#loadMoreBtn');if(!state.query||state.query.trim().length<2){grid.innerHTML='';empty.hidden=false;btn.hidden=true;$('#resultState').textContent=i18n[state.lang].smartSearch;return}empty.hidden=true;const visible=state.view.slice(0,state.shown);grid.innerHTML=visible.map(card).join('');btn.hidden=state.shown>=state.view.length;$('#resultState').textContent=state.lang==='ar'?`${state.view.length.toLocaleString('ar-EG')} نتيجة لـ «${state.query}»`:`${state.view.length.toLocaleString()} results for “${state.query}”`;if(!state.view.length)grid.innerHTML=`<div class="empty-state" style="grid-column:1/-1;min-height:260px"><h3>${state.lang==='ar'?'لم نجد نتيجة مباشرة':'No direct result found'}</h3><p>${state.lang==='ar'?'جرّب جزءًا من الاسم أو المادة الفعالة أو اكتب الاسم بالإنجليزية.':'Try part of the name, active ingredient, or the English spelling.'}</p></div>`}

function byId(id){return state.drugs.find(d=>d._id===id)}
function alternatives(d){const sci=normalize(d.scientific_name);if(!sci)return[];return state.drugs.filter(x=>x._id!==d._id&&x._n.sci===sci).sort((a,b)=>(Number(a.price_egp)||Infinity)-(Number(b.price_egp)||Infinity)).slice(0,12)}
function openDrug(d){const alts=alternatives(d);$('#drugDialogContent').innerHTML=`<div class="modal-body"><div class="drug-hero"><div><h2>${escapeHtml(safe(d.commercial_name_en))}</h2><div class="arabic-name">${escapeHtml(safe(d.commercial_name_ar))}</div></div><div class="modal-price">${money(d.price_egp)} <small>${state.lang==='ar'?'ج.م':'EGP'}</small></div></div><div class="detail-grid">${detail(state.lang==='ar'?'المادة الفعالة':'Active ingredient',d.scientific_name)}${detail(state.lang==='ar'?'الشركة المنتجة':'Manufacturer',d.manufacturer)}${detail(state.lang==='ar'?'التصنيف الدوائي':'Drug class',d.drug_class)}${detail(state.lang==='ar'?'طريق الاستخدام':'Route',d.route)}</div><section class="alternatives"><h3>${state.lang==='ar'?'بدائل بنفس التركيب العلمي':'Alternatives with the same composition'}</h3>${alts.length?`<div class="alt-list">${alts.map(x=>`<div class="alt-item"><strong>${escapeHtml(safe(x.commercial_name_en))}</strong><span>${money(x.price_egp)} ${state.lang==='ar'?'ج.م':'EGP'}</span></div>`).join('')}</div>`:`<p>${state.lang==='ar'?'لا توجد بدائل مطابقة في قاعدة البيانات الحالية.':'No exact alternatives in the current dataset.'}</p>`}</section><div class="source-note">${state.lang==='ar'?`مصدر البيانات المفتوحة: Egyptian Drug Database (CC0)، آخر تحديث معلن: ${DATASET_UPDATED}. الاسم العربي في المصدر مخصص للبحث الصوتي وقد لا يكون الاسم العربي الرسمي. السعر استرشادي ويجب التحقق منه وقت الشراء. لا تستخدم هذه الصفحة لتحديد جرعة دوائية.`:'Open-data source: Egyptian Drug Database (CC0), last declared update: June 2026. Arabic names are search aliases and may not be official marks. Prices are indicative and must be verified. Do not use this page to determine a dose.'}</div></div>`;$('#drugDialog').showModal()}
function detail(label,value){return `<div class="detail-item"><span>${label}</span><strong>${escapeHtml(safe(value))}</strong></div>`}

function toggleFav(d){state.favorites.has(d._id)?state.favorites.delete(d._id):state.favorites.add(d._id);savePrefs();updateFavCount();renderResults()}
function updateFavCount(){$('#favoritesCount').textContent=state.favorites.size}
function openFavorites(){const items=[...state.favorites].map(byId).filter(Boolean);$('#favoritesDialogContent').innerHTML=`<div class="favorites-list"><h2>${state.lang==='ar'?'الأدوية المحفوظة':'Saved medicines'}</h2>${items.length?items.map(d=>`<div class="favorite-row"><div><strong>${escapeHtml(safe(d.commercial_name_en))}</strong><span>${escapeHtml(safe(d.commercial_name_ar))} · ${money(d.price_egp)} ${state.lang==='ar'?'ج.م':'EGP'}</span></div><button type="button" data-remove-fav="${escapeHtml(d._id)}">×</button></div>`).join(''):`<p>${state.lang==='ar'?'لا توجد أدوية في المفضلة بعد.':'No saved medicines yet.'}</p>`}</div>`;$('#favoritesDialog').showModal()}
function toggleCompare(d){const i=state.compare.findIndex(x=>x._id===d._id);if(i>=0)state.compare.splice(i,1);else if(state.compare.length<4)state.compare.push(d);else{alert(state.lang==='ar'?'يمكن مقارنة 4 أدوية كحد أقصى.':'You can compare up to 4 medicines.');return}renderCompareDock();renderResults()}
function renderCompareDock(){const dock=$('#compareDock');dock.hidden=!state.compare.length;$('#compareCount').textContent=`${state.compare.length}/4`;$('#compareItems').innerHTML=state.compare.map(d=>`<span class="compare-pill">${escapeHtml(safe(d.commercial_name_en))}</span>`).join('')}
function openCompare(){if(state.compare.length<2){alert(state.lang==='ar'?'اختر دواءين على الأقل للمقارنة.':'Choose at least two medicines.');return}const rows=[['',...state.compare.map(d=>safe(d.commercial_name_en))],[state.lang==='ar'?'السعر':'Price',...state.compare.map(d=>`${money(d.price_egp)} ${state.lang==='ar'?'ج.م':'EGP'}`)],[state.lang==='ar'?'المادة الفعالة':'Active ingredient',...state.compare.map(d=>safe(d.scientific_name))],[state.lang==='ar'?'الشركة':'Manufacturer',...state.compare.map(d=>safe(d.manufacturer))],[state.lang==='ar'?'التصنيف':'Drug class',...state.compare.map(d=>safe(d.drug_class))],[state.lang==='ar'?'طريق الاستخدام':'Route',...state.compare.map(d=>safe(d.route))]];$('#compareDialogContent').innerHTML=`<div class="compare-table-wrap"><h2>${state.lang==='ar'?'مقارنة الأدوية':'Medicine comparison'}</h2><table class="compare-table">${rows.map((r,i)=>`<tr>${r.map((c,j)=>i===0?`<th>${escapeHtml(c)}</th>`:j===0?`<th>${escapeHtml(c)}</th>`:`<td>${escapeHtml(c)}</td>`).join('')}</tr>`).join('')}</table><div class="source-note">${state.lang==='ar'?'تشابه المادة الفعالة لا يعني أن الاستبدال مناسب لكل مريض. استشر الطبيب أو الصيدلي قبل تغيير الدواء.':'Matching ingredients do not automatically mean substitution is appropriate for every patient. Ask a doctor or pharmacist before switching.'}</div></div>`;$('#compareDialog').showModal()}

function applyLanguage(){document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr';document.body.classList.toggle('en',state.lang==='en');$$('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(i18n[state.lang][k])el.textContent=i18n[state.lang][k]});$$('[data-i18n-placeholder]').forEach(el=>{const k=el.dataset.i18nPlaceholder;if(i18n[state.lang][k])el.placeholder=i18n[state.lang][k]});$('#langBtn').textContent=state.lang==='ar'?'EN':'ع';savePrefs();if(state.ready)hydrate(state.drugs.map(({_i,_id,_n,_score,...d})=>d));renderResults()}
function setTheme(theme){document.body.classList.toggle('dark',theme==='dark');localStorage.setItem('adwya-theme',theme);$('meta[name="theme-color"]').content=theme==='dark'?'#0b1716':'#0b746d'}

$('#searchInput').addEventListener('input',queueSearch);$('#clearSearch').addEventListener('click',()=>{$('#searchInput').value='';runSearch();$('#searchInput').focus()});$$('.chip').forEach(b=>b.addEventListener('click',()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;runSearch()}));$('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;sortView()});$('#loadMoreBtn').addEventListener('click',()=>{state.shown+=PAGE_SIZE;renderResults()});$('#popularSearches').addEventListener('click',e=>{const b=e.target.closest('[data-query]');if(!b)return;$('#searchInput').value=b.dataset.query;runSearch();window.scrollTo({top:250,behavior:'smooth'})});
$('#resultsGrid').addEventListener('click',e=>{const cardEl=e.target.closest('.drug-card');if(!cardEl)return;const d=byId(cardEl.dataset.id);if(!d)return;const action=e.target.closest('button')?.dataset.action;if(action==='favorite')toggleFav(d);else if(action==='compare')toggleCompare(d);else if(action==='details')openDrug(d)});
$('#favoritesBtn').addEventListener('click',openFavorites);$('#favoritesDialogContent').addEventListener('click',e=>{const id=e.target.dataset.removeFav;if(!id)return;state.favorites.delete(id);savePrefs();updateFavCount();openFavorites()});$('#openCompare').addEventListener('click',openCompare);$$('[data-close]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.close).close()));$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
$('#themeBtn').addEventListener('click',()=>setTheme(document.body.classList.contains('dark')?'light':'dark'));$('#langBtn').addEventListener('click',()=>{state.lang=state.lang==='ar'?'en':'ar';applyLanguage()});

setTheme(localStorage.getItem('adwya-theme')||((matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light'));applyLanguage();updateFavCount();loadData();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
