let drugs=[],byUid=new Map(),ready=false;
const LOCAL='data/egyptian-drugs.json';
const FALLBACK='https://raw.githubusercontent.com/karem505/egyptian-drug-database/main/data/egyptian-drugs.json';
function normalize(v=''){return String(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[إأآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/ة/g,'ه').replace(/[ًٌٍَُِّْـ]/g,'').replace(/[ضظ]/g,'ظ').replace(/[ذز]/g,'ز').replace(/[ثس]/g,'س').replace(/[^a-z0-9\u0600-\u06ff%]+/g,' ').replace(/\s+/g,' ').trim()}
function fnv1a(s){let h=0x811c9dc5;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,0x01000193)}return(h>>>0).toString(16).padStart(8,'0')}
function uid(d){return fnv1a([d.commercial_name_en,d.scientific_name,d.manufacturer,d.route].map(x=>x||'').join('|'))}
function grams(s){s=normalize(s).replace(/\s/g,'');if(s.length<2)return[s];const a=[];for(let i=0;i<s.length-1;i++)a.push(s.slice(i,i+2));return a}
function dice(a,b){const A=grams(a),B=grams(b);if(!A.length||!B.length)return 0;const m=new Map;for(const x of A)m.set(x,(m.get(x)||0)+1);let hit=0;for(const x of B){const n=m.get(x)||0;if(n){hit++;m.set(x,n-1)}}return 2*hit/(A.length+B.length)}
function strengthSig(name=''){const s=String(name).toUpperCase();const hits=s.match(/\b\d+(?:\.\d+)?\s*(?:MG|MCG|G|GM|ML|IU|I\.U\.|%)(?:\s*\/\s*\d+(?:\.\d+)?\s*(?:ML|MG|G|GM))?/g)||[];return hits.map(x=>x.replace(/\s+/g,'')).sort().join('+')}
function publicDrug(d){return{uid:d.uid,commercial_name_en:d.commercial_name_en,commercial_name_ar:d.commercial_name_ar,scientific_name:d.scientific_name,manufacturer:d.manufacturer,drug_class:d.drug_class,route:d.route,price_egp:d.price_egp}}
function score(d,q,filter){const n=d._n;const fields=filter==='name'?[n.en,n.ar]:filter==='ingredient'?[n.sci]:filter==='company'?[n.maker]:filter==='class'?[n.cls]:[n.en,n.ar,n.sci,n.maker,n.cls];let total=0;const words=q.split(' ').filter(Boolean);for(const f of fields){if(!f)continue;let fieldScore=0;if(f===q)fieldScore=150;else if(f.startsWith(q))fieldScore=125;else if(f.includes(q))fieldScore=92;for(const w of words){if(f===w)fieldScore+=18;else if(f.split(' ').some(x=>x.startsWith(w)))fieldScore+=12;else if(f.includes(w))fieldScore+=6}if(fieldScore<55&&q.length>=4){const sim=dice(q,f);if(sim>.66)fieldScore=Math.max(fieldScore,Math.round(sim*78))}total=Math.max(total,fieldScore)}return total}
function countTop(field,limit=24){const m=new Map;for(const d of drugs){const v=String(d[field]||'').trim();if(!v)continue;m.set(v,(m.get(v)||0)+1)}return[...m.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,limit).map(([value,count])=>({value,count}))}
async function fetchJson(url,tries=2){let last;for(let i=0;i<tries;i++){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const text=await r.text();if(!text||text.trim().startsWith('<'))throw new Error('Invalid JSON response');return JSON.parse(text)}catch(e){last=e;if(i<tries-1)await new Promise(r=>setTimeout(r,500*(i+1)))}}throw last||new Error('Fetch failed')}
async function load(){let raw;try{raw=await fetchJson(LOCAL,3)}catch(localErr){try{raw=await fetchJson(FALLBACK,2)}catch(remoteErr){throw new Error('تعذر تحميل قاعدة الأدوية: '+(remoteErr?.message||localErr?.message||'network'))}}if(!Array.isArray(raw)||raw.length<20000)throw new Error('Invalid dataset');drugs=raw.map(d=>{const x={...d};x.uid=uid(x);x._n={en:normalize(x.commercial_name_en),ar:normalize(x.commercial_name_ar),sci:normalize(x.scientific_name),maker:normalize(x.manufacturer),cls:normalize(x.drug_class),route:normalize(x.route)};x._strength=strengthSig(x.commercial_name_en);return x});byUid=new Map(drugs.map(d=>[d.uid,d]));ready=true;const brands=new Set(drugs.map(d=>d._n.en).filter(Boolean)),companies=new Set(drugs.map(d=>d._n.maker).filter(Boolean)),ingredients=new Set(drugs.map(d=>d._n.sci).filter(Boolean));postMessage({type:'ready',meta:{total:drugs.length,brands:brands.size,companies:companies.size,ingredients:ingredients.size},browse:{ingredients:countTop('scientific_name'),companies:countTop('manufacturer'),classes:countTop('drug_class')}})}
function doSearch(m){const q=normalize(m.q);if(!q){postMessage({type:'search',id:m.id,total:0,results:[]});return}const rows=[];for(const d of drugs){const s=score(d,q,m.filter||'all');if(s>25)rows.push({d,s})}switch(m.sort){case'priceAsc':rows.sort((a,b)=>(Number(a.d.price_egp)||Infinity)-(Number(b.d.price_egp)||Infinity)||b.s-a.s);break;case'priceDesc':rows.sort((a,b)=>(Number(b.d.price_egp)||-Infinity)-(Number(a.d.price_egp)||-Infinity)||b.s-a.s);break;case'name':rows.sort((a,b)=>String(a.d.commercial_name_en||'').localeCompare(String(b.d.commercial_name_en||'')));break;default:rows.sort((a,b)=>b.s-a.s||(Number(a.d.price_egp)||Infinity)-(Number(b.d.price_egp)||Infinity))}postMessage({type:'search',id:m.id,total:rows.length,results:rows.slice(0,m.limit||24).map(x=>publicDrug(x.d))})}
function alternatives(m){const d=byUid.get(m.uid);if(!d||!d._n.sci){postMessage({type:'alternatives',uid:m.uid,results:[]});return}const same=drugs.filter(x=>x.uid!==d.uid&&x._n.sci===d._n.sci).map(x=>{const sameRoute=!!d._n.route&&x._n.route===d._n.route;const sameStrength=!!d._strength&&x._strength===d._strength;const rank=(sameRoute?20:0)+(sameStrength?30:0);return{x,rank,match:sameRoute&&sameStrength?'sameStrength':sameRoute?'sameRoute':'activeOnly'}}).sort((a,b)=>b.rank-a.rank||(Number(a.x.price_egp)||Infinity)-(Number(b.x.price_egp)||Infinity)).slice(0,14).map(({x,match})=>({...publicDrug(x),match}));postMessage({type:'alternatives',uid:m.uid,results:same})}
onmessage=async e=>{const m=e.data||{};try{if(m.type==='init'){if(!ready)await load();return}if(!ready)await load();if(m.type==='search')doSearch(m);else if(m.type==='detail')postMessage({type:'detail',drug:byUid.has(m.uid)?publicDrug(byUid.get(m.uid)):null});else if(m.type==='alternatives')alternatives(m);else if(m.type==='favorites')postMessage({type:'favorites',results:(m.uids||[]).map(x=>byUid.get(x)).filter(Boolean).map(publicDrug)});else if(m.type==='compare')postMessage({type:'compare',results:(m.uids||[]).map(x=>byUid.get(x)).filter(Boolean).map(publicDrug)})}catch(err){postMessage({type:'error',message:String(err?.message||err)})}};
