import fs from 'node:fs';import path from 'node:path';
const root=process.cwd(),out=path.join(root,'_site'),site=(process.env.SITE_URL||'https://iegy.github.io/adwya').replace(/\/$/,'');
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
for(const f of ['index.html','styles.css','app.js','search-worker.js','sw.js','manifest.webmanifest','about.html','sources.html','privacy.html'])fs.copyFileSync(path.join(root,f),path.join(out,f));
fs.cpSync(path.join(root,'assets'),path.join(out,'assets'),{recursive:true});fs.cpSync(path.join(root,'data'),path.join(out,'data'),{recursive:true});fs.copyFileSync(path.join(root,'index.html'),path.join(out,'404.html'));
const data=JSON.parse(fs.readFileSync(path.join(root,'data/egyptian-drugs.json'),'utf8'));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fnv1a(s){let h=0x811c9dc5;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,0x01000193)}return(h>>>0).toString(16).padStart(8,'0')}
function uid(d){return fnv1a([d.commercial_name_en,d.scientific_name,d.manufacturer,d.route].map(x=>x||'').join('|'))}
function slug(s){return String(s||'medicine').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,72)||'medicine'}
const urls=[`${site}/`,`${site}/about.html`,`${site}/sources.html`,`${site}/privacy.html`];
const pageStyle=`body{font-family:Arial,sans-serif;max-width:820px;margin:40px auto;padding:20px;color:#103d39;background:#f4f9f8}main{background:#fff;border:1px solid #d9e9e6;border-radius:24px;padding:28px}a{color:#0b8f87}.p{font-size:32px;font-weight:800}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.b{background:#edf7f5;padding:12px;border-radius:12px}.n{color:#6d8582;font-size:13px}.warn{margin-top:20px;padding:12px;border:1px solid #e8d3b8;border-radius:12px}@media(max-width:600px){.grid{grid-template-columns:1fr}}`;
for(const d of data){const id=uid(d),s=slug(d.commercial_name_en),dir=path.join(out,'drug',`${s}-${id}`);fs.mkdirSync(dir,{recursive:true});const url=`${site}/drug/${s}-${id}/`;urls.push(url);const title=`${d.commercial_name_ar||d.commercial_name_en} | أدوية مصر`;const desc=`${d.commercial_name_en||''} — ${d.scientific_name||''} — ${d.manufacturer||''} — ${d.price_egp??''} EGP`;const html=`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${url}"><style>${pageStyle}</style><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'Drug','name':d.commercial_name_en||'', 'activeIngredient':d.scientific_name||'', 'manufacturer':{'@type':'Organization','name':d.manufacturer||''}})}</script></head><body><main><a href="../../">← أدوية مصر</a><h1 class="p">${esc(d.commercial_name_en)}</h1><h2>${esc(d.commercial_name_ar||'')}</h2><div class="grid"><div class="b"><span class="n">المادة الفعالة</span><br>${esc(d.scientific_name||'—')}</div><div class="b"><span class="n">الشركة</span><br>${esc(d.manufacturer||'—')}</div><div class="b"><span class="n">التصنيف</span><br>${esc(d.drug_class||'—')}</div><div class="b"><span class="n">طريق الاستخدام</span><br>${esc(d.route||'—')}</div><div class="b"><span class="n">السعر الاسترشادي</span><br><strong>${esc(d.price_egp??'—')} EGP</strong></div></div><p><a href="../../?drug=${id}">فتح الصفحة التفاعلية وعرض البدائل والمقارنة</a></p><p class="warn">مرجع معلوماتي فقط. لا يصف جرعات ولا يقرر الاستبدال العلاجي، ويجب التحقق من السعر والبيانات الرسمية.</p></main></body></html>`;fs.writeFileSync(path.join(dir,'index.html'),html)}
function groupPages(type,field,label){
  const groups=new Map();
  for(const d of data){const v=String(d[field]||'').trim();if(!v)continue;if(!groups.has(v))groups.set(v,[]);groups.get(v).push(d)}
  for(const [value,items] of groups){const id=fnv1a(value),s=slug(value),dir=path.join(out,type,`${s}-${id}`);fs.mkdirSync(dir,{recursive:true});const url=`${site}/${type}/${s}-${id}/`;urls.push(url);const list=items.slice(0,80).map(d=>`<li><a href="../../?drug=${uid(d)}">${esc(d.commercial_name_en||'')}</a> — ${esc(d.price_egp??'—')} EGP</li>`).join('');const html=`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(value)} | ${label} | أدوية مصر</title><meta name="description" content="${esc(label)}: ${esc(value)} — ${items.length} مستحضر في قاعدة أدوية مصر"><link rel="canonical" href="${url}"><style>${pageStyle}li{margin:9px 0}</style></head><body><main><a href="../../">← أدوية مصر</a><p class="n">${label}</p><h1>${esc(value)}</h1><p>${items.length} مستحضر في قاعدة البيانات الحالية.</p><p><a href="../../?q=${encodeURIComponent(value)}">فتح البحث التفاعلي لكل النتائج</a></p><ul>${list}</ul><p class="warn">المعلومات والأسعار استرشادية ويجب التحقق منها قبل الاستخدام أو الشراء.</p></main></body></html>`;fs.writeFileSync(path.join(dir,'index.html'),html)}
  console.log('Built',groups.size,type,'pages');
}
groupPages('ingredient','scientific_name','المادة الفعالة');groupPages('company','manufacturer','الشركة المنتجة');groupPages('class','drug_class','التصنيف الدوائي');
const xml=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${u}</loc></url>`).join('')}</urlset>`;fs.writeFileSync(path.join(out,'sitemap.xml'),xml);fs.writeFileSync(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${site}/sitemap.xml\n`);console.log('Built',data.length,'drug pages and',urls.length,'sitemap URLs');
